Miscellaneous improvements.
Faithlife/FaithlifeJson pull request #10
Opened 2017-10-27 14:43 UTC by ejball

2017-10-27 16:20 UTC, bgrainger requested changes
Need to update VersionHistory.md with the scope of these changes.

2017-10-27 17:29 UTC, ejball commented
@bgrainger, prepped for release.

2017-10-30 15:37 UTC, ejball commented
@bgrainger, barring objection, will merge and deploy.

2017-10-30 15:56 UTC, bgrainger approved these changes

2017-10-30 15:56 UTC, merged